name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  build-python-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python publish_lib.py ${{ secrets.GITHUB_TOKEN }}
