name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  pack-test-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      - id: pack-test-pages
        run: python scripts/pack_test_pages.py
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ steps.pack-test-pages.outputs.artifact }}
          retention-days: 30

  deploy-test-pages:
    runs-on: ubuntu-latest
    needs: pack-test-pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-test-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      # - run: python scripts/build_test_docker_image.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}

  publish-test-npm-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: src/package-lock.json
      - run: pip install -r requirements.txt
      - run: npm ci
        working-directory: src
      - run: python scripts/publish_test_npm_package.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}

  build-python-lib:
    runs-on: ubuntu-latest
    needs:
      - deploy-test-pages
      - build-test-docker-image
      - publish-test-npm-package
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      - run: python scripts/publish_lib.py ${{ secrets.GITHUB_TOKEN }}
